2017-09-21 11:30:44 testresult.py methed:handle_test_begin line:371 INFO - 测试用例:UIERGODI05 所有者:YorickYe 优先级:High 超时:360分钟

2017-09-21 11:30:44 luadriver.py methed:creatLuaDriver line:47 INFO - creat luadriver
2017-09-21 11:30:45 remote_connection.py methed:__init__ line:222 INFO - Could not get IP address for host: 127.0.0.1
2017-09-21 11:30:46 luadriver.py methed:creatLuaDriver line:53 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\luadriver.py", line 50, in creatLuaDriver
    __global_luadriver=webdriver.Remote(luaurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium_rainbow\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium_rainbow\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium_rainbow\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium_rainbow\webdriver\remote\webdriver.py", line 254, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium_rainbow\webdriver\remote\remote_connection.py", line 479, in execute
    return self._request(command_info[0], url, body=data)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium_rainbow\webdriver\remote\remote_connection.py", line 540, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "D:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "D:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "D:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "D:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10061] >

2017-09-21 11:30:48 element.py methed:screenshot line:115 INFO - 截图失败
2017-09-21 11:31:26 testresult.py methed:handle_test_begin line:371 INFO - 测试用例:UIERGODI05 所有者:YorickYe 优先级:High 超时:360分钟

2017-09-21 11:31:26 luadriver.py methed:creatLuaDriver line:47 INFO - creat luadriver
2017-09-21 11:31:38 luadriver.py methed:creatLuaDriver line:53 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\luadriver.py", line 50, in creatLuaDriver
    __global_luadriver=webdriver.Remote(luaurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium_rainbow\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium_rainbow\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium_rainbow\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium_rainbow\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium_rainbow\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity


2017-09-21 11:31:40 element.py methed:screenshot line:115 INFO - 截图失败
2017-09-21 11:31:48 luadriver.py methed:closeLuadriver line:56 INFO - close luadriver
2017-09-21 11:31:50 element.py methed:screenshot line:115 INFO - 截图失败
2017-09-21 11:31:50 testresult.py methed:handle_test_end line:386 INFO - 测试用例执行时间: 00:01:5.99

2017-09-21 11:32:39 luadriver.py methed:closeLuadriver line:56 INFO - close luadriver
2017-09-21 11:32:41 element.py methed:screenshot line:115 INFO - 截图失败
2017-09-21 11:32:41 testresult.py methed:handle_test_end line:386 INFO - 测试用例执行时间: 00:01:15.07

2017-09-21 11:36:05 testresult.py methed:handle_test_begin line:371 INFO - 测试用例:UIERGODI05 所有者:YorickYe 优先级:High 超时:360分钟

2017-09-21 11:36:05 luadriver.py methed:creatLuaDriver line:47 INFO - creat luadriver
2017-09-21 11:37:30 luadriver.py methed:closeLuadriver line:56 INFO - close luadriver
2017-09-21 11:37:37 testresult.py methed:handle_test_end line:386 INFO - 测试用例执行时间: 00:01:31.97

2017-09-21 11:41:32 testresult.py methed:handle_test_begin line:371 INFO - 测试用例:UIERGODI05 所有者:YorickYe 优先级:High 超时:360分钟

2017-09-21 11:41:32 luadriver.py methed:creatLuaDriver line:47 INFO - creat luadriver
2017-09-21 11:42:59 luadriver.py methed:closeLuadriver line:56 INFO - close luadriver
2017-09-21 11:43:06 testresult.py methed:handle_test_end line:386 INFO - 测试用例执行时间: 00:01:33.78

2017-09-21 11:43:18 testresult.py methed:handle_test_begin line:371 INFO - 测试用例:UIERGODI05 所有者:YorickYe 优先级:High 超时:360分钟

2017-09-21 11:43:18 luadriver.py methed:creatLuaDriver line:47 INFO - creat luadriver
2017-09-21 11:44:43 luadriver.py methed:closeLuadriver line:56 INFO - close luadriver
2017-09-21 11:44:49 testresult.py methed:handle_test_end line:386 INFO - 测试用例执行时间: 00:01:31.39

2017-09-21 11:44:55 testresult.py methed:handle_test_begin line:371 INFO - 测试用例:UIERGODI05 所有者:YorickYe 优先级:High 超时:360分钟

2017-09-21 11:44:55 luadriver.py methed:creatLuaDriver line:47 INFO - creat luadriver
2017-09-21 11:46:22 luadriver.py methed:closeLuadriver line:56 INFO - close luadriver
2017-09-21 11:46:29 testresult.py methed:handle_test_end line:386 INFO - 测试用例执行时间: 00:01:34.48

